version: '3.8'

services:
  docling-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - NEON_CONNECTION_STRING=${NEON_CONNECTION_STRING}
      - EMBEDDING_PROVIDER=${EMBEDDING_PROVIDER:-openai}
    volumes:
      - ./data:/app/data
      - ./cache:/app/cache
      - ./output:/app/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import streamlit; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
        reservations:
          memory: 1G
          cpus: '0.5'