"""Add system_prompt table

Revision ID: 1b89493c4887
Revises: fix_chunk_text_index
Create Date: 2025-10-23 14:47:00.006995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b89493c4887'
down_revision: Union[str, Sequence[str], None] = 'fix_chunk_text_index'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_prompt_id'), 'system_prompt', ['id'], unique=False)
    op.drop_index(op.f('idx_chunks_text_gin'), table_name='document_chunks', postgresql_using='gin')
    op.drop_index(op.f('idx_chunks_text_hash'), table_name='document_chunks')
    op.create_index('idx_chunks_text', 'document_chunks', ['chunk_text'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunks_text', table_name='document_chunks', postgresql_using='gin')
    op.create_index(op.f('idx_chunks_text_hash'), 'document_chunks', [sa.literal_column('md5(chunk_text)')], unique=False)
    op.create_index(op.f('idx_chunks_text_gin'), 'document_chunks', [sa.literal_column("to_tsvector('french'::regconfig, chunk_text)")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_system_prompt_id'), table_name='system_prompt')
    op.drop_table('system_prompt')
    # ### end Alembic commands ###
